# A docker image that contains the PyPA manylinux_2_28 toolchain
#
# Usage:
# $ DOCKER_BUILDKIT=1 docker build -f docker/manylinux_2_28/Dockerfile_x86_64 -t mp_manylinux .
# $ docker run -it --name mp_pip_package_container -d mp_manylinux:latest bash

# Make a container for MediaPipe
FROM quay.io/pypa/manylinux_2_28_x86_64:2026.07.11-2


ARG NINJA_VERSION=1.13.2
ARG LIB_OPENMPT_VERSION=0.8.7


# Install Ninja
RUN mkdir -p /opt/ninja/build /opt/ninja/src && \
    cd /opt/ninja && \
    curl -L https://github.com/ninja-build/ninja/archive/refs/tags/v${NINJA_VERSION}.tar.gz -o ninja.tar.gz && \
    tar -xf ninja.tar.gz -C /opt/ninja/src --strip-components 1 && \
    cmake -S /opt/ninja/src -B /opt/ninja/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/ninja/install && \
    cmake --build /opt/ninja/build --target ninja -j$(nproc) && \
    mv /opt/ninja/build/ninja /usr/local/bin/ && \
    cd /opt/ninja && \
    rm -rf src build ninja.tar.gz


# Install OpenGL
RUN yum install -y mesa-libGL-devel mesa-libEGL-devel mesa-libGLES-devel mesa-libGLU-devel && \
    yum install -y epel-release && \
    yum install -y emacs libXcursor-devel zip && \
    yum clean all


# Install other dependencies
RUN yum install -y autoconf-archive libtool readline-devel \
    perl-IPC-Cmd perl-Test-Simple perl-Time-Piece perl-open && \
    yum clean all


# Prioritize /usr/local
ENV PATH="/usr/local/bin:$PATH"
ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"


# GitHub Actions user`s UID is 1001
RUN useradd ci -m -s /bin/bash -G users --uid=1001 && \
    mkdir /io && \
    chown -R ci:ci /io && \
    # This calls in mutlibuild scripts and cannot be run without permissions
    chown -R ci:ci /opt/_internal/pipx/venvs/auditwheel

USER ci


# Git security vulnerability: https://github.blog/2022-04-12-git-security-vulnerability-announced
RUN git config --global --add safe.directory /io


# Allow libopenmpt to be found
ENV LDFLAGS="-L/opt/libopenmpt/install/lib"
ENV PKG_CONFIG_PATH="/opt/libopenmpt/install/lib/pkgconfig:$PKG_CONFIG_PATH"
